server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:45770/railway
    username: postgres
    password: qwLdFevlEEvQdVqDcDwoGaHXMYaHfyqZ
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

app:
  name: order-service
