server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:25093/railway
    username: postgres
    password: QGnlKOBUUqDfZVYSmkUppFWIHHOSRExM
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

app:
  name: order-service
